const {chromium}=require('@playwright/test');
const fs=require('fs');
fs.mkdirSync('test-results', {recursive:true});
(async()=>{
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}});
const manifest={items:[{id:'https://example.org/canvas',type:'Canvas',width:100,height:140,items:[{items:[{body:{id:'https://example.org/page.png',type:'Image',format:'image/png',width:100,height:140}}]}]}]};
await page.route('https://gallica.bnf.fr/**/manifest.json',route=>route.fulfill({json:manifest}));
await page.route('https://example.org/page.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aHTEAAAAASUVORK5CYII=','base64')}));
await page.goto('http://127.0.0.1:5173');
await page.locator('details').first().locator('summary').click();
await page.locator('#apiBase').fill('http://127.0.0.1:8000');
await page.locator('#manuscriptId').fill('browser-fixture');
await page.locator('#loadApi').click();
await page.locator('#status').filter({hasText:'تم ربط'}).waitFor();
await page.locator('#readingMode').selectOption('researcher');
await page.locator('#livingLayers summary').click();
await page.locator('[data-status]').filter({hasText:'لا توجد طبقات جديدة'}).waitFor();
await page.locator('[data-token]').fill(JSON.parse(fs.readFileSync(process.env.BROWSER_FIXTURE_TOKEN_FILE || '/tmp/browser-fixture.json')).token);
await page.locator('[data-text]').fill('Browser draft <img src=x onerror="window.bad=1">');
const post=page.waitForResponse(r=>r.url().endsWith('/api/v1/living/layers')&&r.request().method()==='POST');
await page.getByRole('button',{name:'حفظ مسودة جديدة'}).click();
if((await post).status()!==200)throw new Error('Draft save failed');
await page.locator('[data-layers]').getByText('Browser draft <img src=x onerror="window.bad=1">',{exact:true}).waitFor();
if(await page.evaluate(()=>window.bad))throw new Error('Stored XSS executed');
await page.locator('[data-reviewer]').fill('browser-editor');
const denied=page.waitForResponse(r=>r.url().endsWith('/api/v1/living/layers')&&r.request().method()==='POST');
await page.locator('[data-verify]').click();
if((await denied).status()!==403)throw new Error('Transcriber verification was allowed');
await page.screenshot({path:'test-results/layers-mobile.png',fullPage:true});
await page.reload();
await page.locator('details').first().locator('summary').click();
await page.locator('#apiBase').fill('http://127.0.0.1:8000');
await page.locator('#manuscriptId').fill('browser-fixture');
await page.locator('#loadApi').click();
await page.locator('#livingLayers summary').click();
await page.locator('[data-layers]').getByText('Browser draft <img src=x onerror="window.bad=1">',{exact:true}).waitFor();
console.log('PASS: mobile draft creation, server authorization, escaped content and reload persistence');
await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
