const {chromium}=require('@playwright/test');
const fs=require('fs');
fs.mkdirSync('test-results', {recursive:true});
(async()=>{
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}});
const manifest={items:[{id:'https://example.org/canvas',type:'Canvas',width:100,height:140,items:[{items:[{body:{id:'https://example.org/page.png',type:'Image',format:'image/png',width:100,height:140}}]}]}]};
await page.route('https://gallica.bnf.fr/**/manifest.json',route=>route.fulfill({json:manifest}));
await page.route('https://example.org/page.png',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aHTEAAAAASUVORK5CYII=','base64')}));
await page.goto('http://127.0.0.1:5173');
await page.locator('details').first().locator('summary').click();
await page.locator('#apiBase').fill('http://127.0.0.1:8000');
await page.locator('#manuscriptId').fill('browser-fixture');
await page.locator('#loadApi').click();
await page.locator('#status').filter({hasText:'تم ربط'}).waitFor();
await page.locator('#readingMode').selectOption('researcher');
await page.locator('#livingLayers summary').click();
await page.locator('#livingLayers [data-status]').filter({hasText:'لا توجد طبقات جديدة'}).waitFor();
await page.locator('#livingLayers [data-token]').fill(JSON.parse(fs.readFileSync(process.env.BROWSER_FIXTURE_TOKEN_FILE || '/tmp/browser-fixture.json')).token);
await page.locator('#livingLayers [data-text]').fill('Browser draft <img src=x onerror="window.bad=1">');
const post=page.waitForResponse(r=>r.url().endsWith('/api/v1/living/layers')&&r.request().method()==='POST');
await page.getByRole('button',{name:'حفظ مسودة جديدة'}).click();
if((await post).status()!==200)throw new Error('Draft save failed');
await page.locator('#livingLayers [data-layers]').getByText('Browser draft <img src=x onerror="window.bad=1">',{exact:true}).waitFor();
if(await page.evaluate(()=>window.bad))throw new Error('Stored XSS executed');
await page.locator('#livingLayers [data-reviewer]').fill('browser-editor');
const denied=page.waitForResponse(r=>r.url().endsWith('/api/v1/living/layers')&&r.request().method()==='POST');
await page.locator('#livingLayers [data-verify]').click();
if((await denied).status()!==403)throw new Error('Transcriber verification was allowed');
await page.screenshot({path:'test-results/layers-mobile.png',fullPage:true});
await page.reload();
await page.locator('details').first().locator('summary').click();
await page.locator('#apiBase').fill('http://127.0.0.1:8000');
await page.locator('#manuscriptId').fill('browser-fixture');
await page.locator('#loadApi').click();
await page.locator('#livingLayers summary').click();
await page.locator('#livingLayers [data-layers]').getByText('Browser draft <img src=x onerror="window.bad=1">',{exact:true}).waitFor();
const ota = page.locator('#ottomanLab');
await ota.locator('summary').click();
await ota.locator('[data-refresh]').click();
await ota.locator('[data-message]').filter({hasText:'لا توجد مراحل'}).waitFor();
await ota.locator('[data-token]').fill(JSON.parse(fs.readFileSync('/tmp/browser-fixture.json')).token);
await ota.locator('[data-stage]').selectOption('transcription');
await ota.locator('[data-text]').fill('Synthetic Ottoman fixture, no historical assertion');
let saved=page.waitForResponse(r=>r.url().endsWith('/api/v1/ottoman/revisions')&&r.request().method()==='POST');
await ota.getByRole('button',{name:'حفظ مرحلة مستقلة'}).click();
if((await saved).status()!==200)throw new Error('Ottoman transcription save failed');
await ota.locator('[data-history]').getByText('Synthetic Ottoman fixture, no historical assertion',{exact:true}).waitFor();
await ota.locator('[data-stage]').selectOption('transliteration');
await ota.locator('[data-input] option').first().waitFor({state:'attached'});
await ota.locator('[data-text]').fill('Separate Latin fixture');
saved=page.waitForResponse(r=>r.url().endsWith('/api/v1/ottoman/revisions')&&r.request().method()==='POST');
await ota.getByRole('button',{name:'حفظ مرحلة مستقلة'}).click();
if((await saved).status()!==200)throw new Error('Ottoman transliteration save failed');
await ota.locator('[data-history]').getByText('Separate Latin fixture',{exact:true}).waitFor();
await page.screenshot({path:'test-results/ottoman-mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth + 1))throw new Error('Mobile horizontal overflow');
await page.locator('#manuscriptId').fill('academy-browser');
await page.locator('#loadApi').click();
const academy = page.locator('#ottomanAcademy');
await academy.locator('summary').click();
await academy.getByRole('button',{name:'تحميل تمارين الصفحة'}).click();
await academy.getByText('Synthetic browser exercise',{exact:true}).waitFor();
await academy.locator('[data-query]').fill('Synthetic dictionary');
await academy.getByRole('button',{name:'بحث',exact:true}).click();
await academy.getByText('Synthetic meaning',{exact:true}).waitFor();
await academy.getByRole('textbox',{name:'محاولة قراءة النص العثماني'}).fill('Synthetic original exercise');
await academy.getByRole('button',{name:'تحقق من المحاولة'}).click();
await academy.getByText('مطابقة للنص المراجع. هذا تدريب، وليس اعتمادًا علميًا.',{exact:true}).waitFor();
await academy.getByRole('button',{name:'اكشف المرحلة التالية'}).click();
await academy.getByText('transcription: Synthetic original exercise',{exact:true}).waitFor();
await academy.getByRole('button',{name:'اكشف المرحلة التالية'}).click();
await academy.getByText('transliteration: Synthetic Latin exercise',{exact:true}).waitFor();
await page.screenshot({path:'test-results/academy-mobile.png',fullPage:true});
const heritage = page.locator('#heritageGraph');
await heritage.locator('summary').click();
await heritage.locator('[data-query]').fill('Synthetic historical');
await heritage.getByRole('button',{name:'ابحث في المعرفة'}).click();
await heritage.getByRole('heading',{name:'Synthetic historical place'}).waitFor();
await heritage.getByRole('button',{name:'افتح الفترة'}).click();
await heritage.getByRole('heading',{name:'Synthetic historical place'}).waitFor();
await heritage.getByRole('button',{name:'أماكن الفترة'}).click();
await heritage.getByRole('link').filter({hasText:'Synthetic historical place'}).waitFor();
await page.screenshot({path:'test-results/heritage-mobile.png',fullPage:true});
await heritage.locator('[data-question]').fill('verified corpus');
await heritage.getByRole('button',{name:'اسأل التراث',exact:true}).click();
await heritage.locator('[data-answer]').getByText(/Synthetic verified corpus excerpt/).waitFor();
const museum=page.locator('#livingMuseum');await museum.locator('summary').click();
await museum.getByRole('button',{name:'تحميل المعارض'}).click();
await museum.getByRole('button',{name:'ادخل المعرض'}).click();
await museum.getByRole('heading').filter({hasText:'Synthetic museum object'}).waitFor();
await museum.getByText(/إعادة بناء تفسيرية/).waitFor();
await page.screenshot({path:'test-results/museum-mobile.png',fullPage:true});
console.log('PASS: living layers, Ottoman stages, academy, graph, time/map, museum and verified heritage excerpts');
await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
